# playbook.yml
---
- name: Sample dynamic inventory
  hosts: "{{ target_hosts }}"

  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/ansible-key.id_rsa

  tasks:
    - name: Print Name tag
      debug:
        msg: "{{ tags.Name }}"
