version: "3"

services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    volumes:
      - type: bind
        source: "../app"
        target: "/app"
      - type: bind
        source: "${HOME}/.aws"
        target: "/root/.aws"
    working_dir: /app
    entrypoint: ["/bin/ash"]
    tty: true
