version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name ${code-deploy-app-name} --s3-location s3://${s3-bucket-name}/artifact.zip --source ${src}
artifacts:
  files:
    - "**/*"
  base-directory: ${src}
