#cloud-config
timezone: ${timezone}

packages:
  - git
  - wget

runcmd:
  - wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
  - dpkg -i amazon-ssm-agent.deb
  - git clone https://github.com/dtag-dev-sec/tpotce /root/tpot
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
  - sudo reboot

password: ${password}
chpasswd:
  expire: false

write_files:
  - content: |
      # tpot configuration file
      myCONF_TPOT_FLAVOR='${tpot_flavor}'
      myCONF_WEB_USER='${web_user}'
      myCONF_WEB_PW='${web_password}'
    owner: root:root
    path: /root/tpot.conf
    permissions: '0600'